- name: Setup SSH
run: |
  mkdir -p ~/.ssh
  echo -e "Host github.com\n\tIdentityFile ~/.ssh/id_ed25519\n\tStrictHostKeyChecking no" >> ~/.ssh/config
  chmod 600 ~/ssh/id_ed25519
  ssh-keyscan -H github.com >> ~/.ssh/known_hosts
